version: '3.4'

services:
  sourcingdb:
    container_name: sourcingdb
    restart: always
    volumes:
        - ${WEBAPP_STORAGE_HOME}/site:/data/db
    ports:
        - "27017:27017"

  rabbitmq:
    container_name: sourcing_rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  sourcingsqldb:
    container_name: sourcingsqldb
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Odb123456789"
      ACCEPT_EULA: "Y"

  tutorial.products:
    container_name: esourcing_product
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ProductDatabaseSettings:ConnectionStrings=mongodb://sourcingdb:27017"
    depends_on:
      - sourcingdb
    ports:
      - "8000:80"
    volumes:
      - ${HOME}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets

  tutorial.sourcing:
    container_name: esourcing_sourcing
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "SourcingDatabaseSettings:ConnectionString=mongodb://sourcingdb:27017"
      - "EventBus:HostName=rabbitmq"
    depends_on:
      - sourcingdb
      - rabbitmq
    volumes:
      - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
      - ${HOME}/.aspnet/Https:/root/.aspnet/https/
    ports:
      - "8001:80"

  tutorial.orders:
    container_name: esourcing_order
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:OrderConnection=Server=sourcingsqldb;Database=OrderDb;User Id=sa;Password=Odb123456789"
      - "EventBus:HostName=rabbitmq"
    depends_on:
      - sourcingsqldb
      - rabbitmq
    volumes:
      - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
      - ${HOME}/.aspnet/Https:/root/.aspnet/https/
    ports:
      - "8002:80"

  tutorial.apigateway:
    container_name: esourcing_apigateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - tutorial.products
      - tutorial.sourcing
      - tutorial.orders
    ports:
      - "5000:80"
    volumes:
      - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
      - ${HOME}/.aspnet/https:/root/.aspnet/https

